---
fail_fast: false

repos:

  - repo: local
    hooks:
      - id: detect-secrets
        name: Detect Secrets
        description: This hook detects and prevents high entropy strings from entering the codebase.
        entry: hooks/detect-secrets
        language: python
        files: .*

      - id: check-mailmap
        name: Detect if an email address needs to be added to mailmap
        language: script
        entry: hooks/check-mailmap
        always_run: true  # Run on every commit.
        exclude: .*       # Otherwise runs once per file.

      - id: forbid-binary
        name: forbid-binary (local)
        language: script
        entry: hooks/forbid-binary
        types: ['binary']
        exclude: >
          (?x)^(
            ci/fixtures/one-byte-binary
          )$

      - id: forbid-space-in-indent
        name: forbid-space-in-indent (local)
        language: script
        entry: hooks/forbid-space-in-indent
        exclude: ^.*$

      - id: git-dirty
        name: git-dirty (local)
        language: script
        entry: hooks/git-dirty

      - id: require-ascii
        name: file encoding (local)
        description: Ensure file is ascii-encoded
        entry: hooks/require-ascii.py
        language: python
        types: [text]
        exclude: ^ci/ansi$  # 3rd-party script

      - id: shellcheck
        name: shellcheck (local)
        language: script
        entry: hooks/shellcheck
        types: [shell]
        args: [-e, SC1091]
        additional_dependencies: [shellcheck]

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.1.0
    hooks:
      - id: check-added-large-files
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: detect-private-key

  - repo: https://github.com/imjoseangel/pre-commit-hooks
    rev: master
    hooks:
      - id: detect-secrets
